### ISSUE TITLE
Request Fitur Di video YT di menit 7:02 video yg baru di upload 🗿

### ISSUE THREAD

**Issue by Yuri-Neko** [FahriAdison/Sad-Multi-Device#1]
7:02 coba pake nya link bukan media dari file bot.. Contoh kek gini

let handler = async (m, { conn, command }) => {
	m.reply('_*Wait*_ 🐦')
  let audio = ` https://raw.githubusercontent.com/saipulanuar/Api-Github/main/audio/${command}.mp3 `
  await conn.sendFile(m.chat, audio, 'error.mp3', null, m, true)
}

handler.command = handler.help = [
'anjay', 
'ara-ara', 
'ara-ara-cowok', 
'ara-ara2',
'arigatou', 
'assalamualaikum', 
'asu', 
'ayank', 
'aku-ngakak', 
'bacot', 
'bahagia-aku',
'baka', 
'bansos', 
'beat-box', 
'beat-box2', 
'biasalah', 
'bidadari', 
'bot', 
'buka-pintu', 
'canda-anjing', 
'cepetan', 
'cuekin-terus', 
'daisuki-dayo', 
'daisuki',
 'dengan-mu', 
'gaboleh-gitu', 
'gak-lucu', 
'gamau', 
'gay', 
'gelay', 
'gitar', 
'gomenasai', 
'hai-bot',
'hampa', 
'hayo', 
'hp-iphone', 
'i-like-you', 
'ih-wibu', 
'india', 
'karna-lo-wibu', 
'kiss',
'kontol', 
'ku-coba', 
'maju-wibu', 
'makasih', 
'mastah', 
'nande-nande', 
'nani', 
'ngadi-ngadi', 
'nikah', 'nuina', 
'onichan', 
'owner-sange', 
'ownerku', 
'pak-sapardi', 
'pale', 
'pantek', 
'pasi-pasi',
 'punten', 
'sayang', 
'siapa-sih', 
'sudah-biasa', 
'summertime', 
'tanya-bapak-lu', 
'to-the-bone', 
'wajib', 
'waku', 
'woi',
 'yamete', 
'yowaimo', 
'yoyowaimo'
]
handler.tags = ['vn']
handler.owner = false
export default handler

SC yg gw pake zabot md.. .Tinggal tar edit² sendiri  biar bisa di SC Sad-Bot-MD

🗿cuma mau comment gitu.. Malah di hapus sama yt.. Btw itu source code nya 
Coba jadi ndak di SadBot-MD
Klo nggak tinggal di edit² sendiri :v

Di link github file nya kasih kutip dua ( ` ) 
🗿ntah kenapa keliatan tulisan di link nya kaya tebel klo ada dua kutip gitu.. Jadi ku kasih tau aja kli aja error

**Comment by FahriAdison** [comment]
thx

**Comment by FahriAdison** [comment]
Ok Done
