### ISSUE TITLE
imagemagick

### ISSUE THREAD

**Issue by Yuri-Neko** [FahriAdison/Sad-Multi-Device#5]
https://github.com/DuckyTeam/heroku-buildpack-imagemagick.git

nggak bisa di pasang di heroku 
apakah gpp klo nggak usah di pake?

ImageMagick app detected
-----> Install ImageMagick
-----> Downloading ImageMagick from https://www.imagemagick.org/download/releases/ImageMagick-7.0.5-10.tar.xz
--2022-06-24 08:02:20--  https://www.imagemagick.org/download/releases/ImageMagick-7.0.5-10.tar.xz
Resolving www.imagemagick.org (www.imagemagick.org)... 50.251.58.13
Connecting to www.imagemagick.org (www.imagemagick.org)|50.251.58.13|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://download.imagemagick.org/archive/releases/ImageMagick-7.0.5-10.tar.xz [following]
--2022-06-24 08:02:20--  https://download.imagemagick.org/archive/releases/ImageMagick-7.0.5-10.tar.xz
Resolving download.imagemagick.org (download.imagemagick.org)... 50.251.58.13
Connecting to download.imagemagick.org (download.imagemagick.org)|50.251.58.13|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2022-06-24 08:02:20 ERROR 404: Not Found.
-----> Extracting ImageMagick from /tmp/build_34970041/ImageMagick-7.0.5-10.tar.xz
       Error: Unable to download ImageMagick
       app.json
       config.js
       docker-compose.yml
       Dockerfile
       handler.js
       index.js
       lib
       LICENSE
       main.js
       media
       names.fnt
       names.png
       node_modules
       null.png
       package.json
       package-lock.json
       papah2.hx
       papah2.java
       papah2.py
       papah3.hx
       papah3.py
       papah4.hx
       papah4.py
       papah.c
       papah-copy.c
       papah-copy.cs
       papah-copy.d
       papah-copy.dart
       papah-copy.hack
       papah-copy.hx
       papah.cs
       papah.css
       papah.d
       papah.dart
       papah-frame.java
       papah.hack
       papah.html
       papah.hx
       papah.java
       papah.js
       papah.php
       papah.py
       papah.rb
       papah.vue
       plugins
       Procfile
       README.md
       replit.nix
       ress.webp
       server.js
       session.data.json
       speed.py
       src
       test.js
       testt.webp
       thumbnail.jpg
       tmp
       upload.sh
       vendor
       views
 !     Push rejected, failed to compile ImageMagick app.
 !     Push failed

**Comment by FahriAdison** [comment]
ntar w pikirkan

**Comment by VERDIBOTZ1** [comment]
Hai banh

**Comment by VERDIBOTZ1** [comment]
Wahaha
